language: node_js
node_js:
  - 0.12
before_script:
  - npm install -g grunt-cli
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libgif-dev libopencv-dev libjpeg8-dev libpango1.0-dev build-essential g++
  - sudo add-apt-repository -y ppa:lyrasis/precise-backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake build-essential gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg-dev libpng12-dev libwebp-dev libtiff4-dev libexif-dev libgsf-1-dev liblcms2-dev libxml2-dev swig libmagickcore-dev
  - sudo ./install-libvips.sh
script:
  - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
  - export LD_LIBRARY_PATH=/usr/local/lib
