language: node_js
node_js:
  - 0.12
before_script:
  - npm install -g grunt-cli
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libvips-dev libcairo2-dev libgif-dev libopencv-dev libjpeg8-dev libpango1.0-dev build-essential g++
